# CRS station codes can be found here => https://en.wikipedia.org/wiki/UK_railway_stations_%E2%80%93_A
homeStation:
  name: "London St Pancras International"
  crs: "STP"

# Engineering works will look for disruptions affecting this operator
# https://en.wikipedia.org/wiki/List_of_companies_operating_trains_in_the_United_Kingdom
operatorCodes: 
  - "TL" # Thameslink
#  - "LE" # Greater Anglia
#  - "XR" # Elizabeth Line
#  - "LO" # London Overground
#  - "LT" # London Underground (Tube)

destinations:
  - id: "stalbans"
    name: "St Albans"
    crs: "SAC"
  - id: "flitwick"
    name: "Flitwick"
    crs: "FLT"
  - id: "bedford"
    name: "Bedford"
    crs: "BDM"

walkTimeMins: 10
